name: CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Create application.yml
        run: echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Spring Boot application
        run: ./gradlew bootJar

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend . -f Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend

      - name: SSH to server and deploy Docker container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker rmi -f ${{ secrets.DOCKER_USERNAME }}/backend
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend
            docker stop ${{ secrets.DOCKER_USERNAME }} || true
            docker rm ${{ secrets.DOCKER_USERNAME }} || true
            docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/backend